version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: gunicorn
    versions:
    - 20.0.4
